<a href="https://colab.research.google.com/github/himanshigarg01/bank-marketing-dataset/blob/main/Bank_Marketing_Dataset_(Himanshi).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# important libraries
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv('/content/bank-full.csv', delimiter = ';')

In [ ]:
df.head(5)

   age           job  marital  education default  ...  campaign pdays previous poutcome   y
0   58    management  married   tertiary      no  ...         1    -1        0  unknown  no
1   44    technician   single  secondary      no  ...         1    -1        0  unknown  no
2   33  entrepreneur  married  secondary      no  ...         1    -1        0  unknown  no
3   47   blue-collar  married    unknown      no  ...         1    -1        0  unknown  no
4   33       unknown   single    unknown      no  ...         1    -1        0  unknown  no

[5 rows x 17 columns]

In [ ]:
df.describe()

                age        balance           day  ...      campaign         pdays      previous
count  45211.000000   45211.000000  45211.000000  ...  45211.000000  45211.000000  45211.000000
mean      40.936210    1362.272058     15.806419  ...      2.763841     40.197828      0.580323
std       10.618762    3044.765829      8.322476  ...      3.098021    100.128746      2.303441
min       18.000000   -8019.000000      1.000000  ...      1.000000     -1.000000      0.000000
25%       33.000000      72.000000      8.000000  ...      1.000000     -1.000000      0.000000
50%       39.000000     448.000000     16.000000  ...      2.000000     -1.000000      0.000000
75%       48.000000    1428.000000     21.000000  ...      3.000000     -1.000000      0.000000
max       95.000000  102127.000000     31.000000  ...     63.000000    871.000000    275.000000

[8 rows x 7 columns]

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
# check for imbalanced dataset
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [ ]:
df['marital'].unique()
df['job'].unique()
df['job'].value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=35)
x_os, y_os = smote.fit_resample(df.iloc[:,0:16], df.iloc[:,-1])
print(x_os)

ValueError: could not convert string to float: 'management'

In [ ]:
# split into train and test
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:16], df.iloc[:,-1], test_size = 0.2, random_state = 35)
print(x_train.shape, y_train.shape)

(36168, 16) (36168,)

In [ ]:
ohe = OneHotEncoder(drop = 'first')
x_transformed = ohe.fit_transform(x_train[['marital','job', 'education']])
print(x_transformed)

  (0, 0)	1.0
  (0, 2)	1.0
  (0, 15)	1.0
  (1, 0)	1.0
  (1, 12)	1.0
  (1, 13)	1.0
  (2, 0)	1.0
  (2, 5)	1.0
  (2, 15)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (4, 1)	1.0
  (4, 9)	1.0
  (4, 14)	1.0
  (5, 0)	1.0
  (5, 10)	1.0
  (5, 13)	1.0
  (6, 0)	1.0
  (6, 2)	1.0
  (6, 13)	1.0
  (7, 0)	1.0
  (7, 8)	1.0
  (7, 13)	1.0
  (8, 1)	1.0
  (8, 10)	1.0
  :	:
  (36157, 2)	1.0
  (36157, 13)	1.0
  (36158, 1)	1.0
  (36158, 5)	1.0
  (36158, 14)	1.0
  (36159, 2)	1.0
  (36160, 10)	1.0
  (36160, 13)	1.0
  (36161, 13)	1.0
  (36162, 0)	1.0
  (36162, 2)	1.0
  (36162, 13)	1.0
  (36163, 1)	1.0
  (36163, 5)	1.0
  (36163, 14)	1.0
  (36164, 1)	1.0
  (36164, 13)	1.0
  (36165, 0)	1.0
  (36165, 6)	1.0
  (36165, 13)	1.0
  (36166, 1)	1.0
  (36166, 5)	1.0
  (36166, 14)	1.0
  (36167, 1)	1.0
  (36167, 13)	1.0

In [ ]:
ohe = OneHotEncoder(drop = 'first')
x_transformed = ohe.fit_transform(x_train[['marital','job', 'education']])
print(x_transformed)

In [ ]:
ohe = OneHotEncoder(drop = 'first')
x_test_trans = ohe.fit_transform(x_test[['marital','job', 'education']])
print(x_test_trans)

  (0, 1)	1.0
  (0, 5)	1.0
  (0, 14)	1.0
  (1, 0)	1.0
  (1, 8)	1.0
  (1, 15)	1.0
  (2, 0)	1.0
  (2, 5)	1.0
  (2, 14)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (3, 13)	1.0
  (4, 1)	1.0
  (4, 10)	1.0
  (4, 14)	1.0
  (5, 0)	1.0
  (5, 5)	1.0
  (5, 14)	1.0
  (6, 0)	1.0
  (6, 10)	1.0
  (6, 13)	1.0
  (7, 0)	1.0
  (7, 10)	1.0
  (7, 14)	1.0
  (8, 0)	1.0
  :	:
  (9032, 0)	1.0
  (9032, 6)	1.0
  (9033, 1)	1.0
  (9033, 8)	1.0
  (9033, 13)	1.0
  (9034, 0)	1.0
  (9034, 2)	1.0
  (9035, 0)	1.0
  (9035, 10)	1.0
  (9035, 13)	1.0
  (9036, 0)	1.0
  (9036, 13)	1.0
  (9037, 0)	1.0
  (9037, 2)	1.0
  (9038, 0)	1.0
  (9038, 11)	1.0
  (9038, 14)	1.0
  (9039, 0)	1.0
  (9039, 5)	1.0
  (9039, 14)	1.0
  (9040, 5)	1.0
  (9040, 14)	1.0
  (9041, 13)	1.0
  (9042, 1)	1.0
  (9042, 2)	1.0

In [ ]:
lb = LabelEncoder()
y_train_enc = lb.fit_transform(y_train)
y_test_enc = lb.fit_transform(y_test)

In [ ]:
model = RandomForestClassifier(random_state=42, )
model.fit(x_transformed, y_train_enc)
y_pred = model.predict(x_test_trans)

In [ ]:
accuracy = accuracy_score(y_test_enc, y_pred)
print(accuracy)

0.8812341037266394

In [ ]:
report = classification_report(y_test_enc, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94      7969
           1       0.00      0.00      0.00      1074

    accuracy                           0.88      9043
   macro avg       0.44      0.50      0.47      9043
weighted avg       0.78      0.88      0.83      9043

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))